"""initial migration for tables

Revision ID: c969c1a6a2ff
Revises: 8b2fc4ad120d
Create Date: 2025-10-18 14:51:44.381252

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c969c1a6a2ff"
down_revision: Union[str, Sequence[str], None] = "8b2fc4ad120d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table("namespaces",
    sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
    sa.Column("name", sa.String(length=256), nullable=False),
    sa.Column("description", sa.String(), nullable=True),
    sa.PrimaryKeyConstraint("id"),
    sa.UniqueConstraint("name"),
    )
    op.create_table("tables",
    sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
    sa.Column("name", sa.String(length=256), nullable=False),
    sa.Column("verbose_name", sa.String(length=256), nullable=False),
    sa.Column("description", sa.String(), nullable=True),
    sa.Column("namespace_id", sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(["namespace_id"], ["namespaces.id"] ),
    sa.PrimaryKeyConstraint("id"),
    sa.UniqueConstraint("name"),
    )
    op.create_table("fields",
    sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
    sa.Column("table_id", sa.Integer(), nullable=False),
    sa.Column("name", sa.String(length=256), nullable=False),
    sa.Column("verbose_name", sa.String(length=256), nullable=False),
    sa.Column("data_type", sa.Enum("INT", "FLOAT", "STRING", "BOOL", "DATETIME", name="datatypeenum", native_enum=False), nullable=False),
    sa.Column("is_nullable", sa.Boolean(), nullable=False),
    sa.Column("default_value", sa.String(length=256), nullable=True),
    sa.ForeignKeyConstraint(["table_id"], ["tables.id"] ),
    sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("fields")
    op.drop_table("tables")
    op.drop_table("namespaces")
    # ### end Alembic commands ###
